export enum FieldType {
  TEXT = 'TEXT',
  TEXTAREA = 'TEXTAREA',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  DATETIME = 'DATETIME',
  URL = 'URL',
  DROPDOWN = 'DROPDOWN',
  MULTI_DROPDOWN = 'MULTI_DROPDOWN',
  USER = 'USER',
  MULTI_USER = 'MULTI_USER',
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
  BOOLEAN = 'BOOLEAN',
}

